robot moved from countertop to fridge
robot picks up honey from fridge
robot moved from fridge to countertop
robot puts down honey to countertop
robot moved from countertop to cabinet
robot picks up vanilla_extract from cabinet
robot moved from cabinet to countertop
robot puts down vanilla_extract to countertop
robot moved from countertop to cabinet
robot picks up bowl from cabinet
robot moved from cabinet to sink
robot puts down bowl to sink
bowl successfully cleaned!
robot picks up bowl from sink
robot moved from sink to countertop
robot puts down bowl to countertop
robot picks up brioche from countertop
robot puts down brioche to bowl
robot picks up milk from countertop
robot puts down milk to bowl
robot picks up honey from countertop
robot puts down honey to bowl
robot picks up vanilla_extract from countertop
robot puts down vanilla_extract to bowl
contents of bowl are ['brioche', 'honey', 'milk', 'vanilla_extract']
contents of bowl are stirred!
robot moved from countertop to cabinet
robot picks up cake_pan from cabinet
robot moved from cabinet to countertop
robot puts down cake_pan to countertop
contents of bowl are ['brioche', 'honey', 'milk', 'vanilla_extract']
contents of bowl poured to cake_pan 
robot picks up cake_pan from countertop
robot moved from countertop to oven
robot puts down cake_pan to oven
Traceback (most recent call last):
  File "/home/shivam/Desktop/side_quests/generalisation_project/OKG/frameworks/GPT4/streamlined_for_experiments/for_knowledge_expansion_2/./LLM_only/final_run.py", line 18, in <module>
    slice("bread_pudding", "knife", "./LLM_only/updated_onto.ttl")
  File "/home/shivam/Desktop/side_quests/generalisation_project/OKG/frameworks/GPT4/streamlined_for_experiments/for_knowledge_expansion_2/LLM_only/functions/actions.py", line 1661, in slice
    raise RuntimeError(f"slice({obj}, {tool}, {onto_file}) #{obj} not present int he environment!")
RuntimeError: slice(bread_pudding, knife, ./LLM_only/updated_onto.ttl) #bread_pudding not present int he environment!
