Traceback (most recent call last):
  File "/home/shivam/Desktop/side_quests/generalisation_project/OKG/frameworks/GPT3.5/other_domains/for_knowledge_expansion/./LLM_only/final_run.py", line 3, in <module>
    put_down_rec("charging_pod", "countertop")
  File "/home/shivam/Desktop/side_quests/generalisation_project/OKG/frameworks/GPT3.5/other_domains/for_knowledge_expansion/LLM_only/functions/actions.py", line 909, in put_down_rec
    raise RuntimeError(f"put_down_rec({rec}, {loc}) #couldnt pick {rec}! It is big")
RuntimeError: put_down_rec(charging_pod, countertop) #couldnt pick charging_pod! It is big
